version: 0.2

phases:
  install:
    commands:
      # variables
      - REPOSITORY_URI=https://hub.docker.com/repository/docker/erekjiang/sg-eirp-trainerdata-api
      - ARTIFACT=erekjiang/sg-eirp-trainerdata-api
      - ARTIFACT_TYPE=.jar
      - TAG_NAME=erekjiang/sg-eirp-trainerdata-api
      - DOCKER_HUB_USERNAME=erekjiang
      - echo $AWS_DEFAULT_REGION
      - echo $ARTIFACT
      - echo $ARTIFACT_TYPE
      - echo $REPOSITORY_URI
      - echo $TAG_NAME
      # installation
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
      #- apt-get install -y gradle


  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - ls -lart
      - mvn -s settings.xml -Dmaven.test.skip=true package
      #- echo Gradle Build
      #- chmod +x gradlew
      #- ./gradlew build
      #- gradle build
      - echo Building the Docker image... $TAG_NAME
      - docker build -f DockerFile -t $TAG_NAME .
      - docker tag $TAG_NAME $TAG_NAME
  post_build:
    commands:
      #- docker tag $REPOSITORY_URI:$ARTIFACT $REPOSITORY_URI:$$ARTIFACT
      #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - cat DockerHubLogin.txt | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $TAG_NAME
      #- aws ecs list-services --cluster UngerwECS
      #- aws ecs update-service --cluster UngerwECS --service SpringBootService-Service-XBO2INJQRTEO --task-definition UngerwSpringBootTD

artifacts:
  files:
    - imageDefinitions.json
    - target/EducationProgram*.jar
